### ISSUE TITLE
filter needs a default

### ISSUE THREAD

**Issue by jframbach-nerdwallet** [felixge/node-require-all#18]
var controllers = require('require-all')({
      dirname     :  __dirname + '/controllers',
      excludeDirs :  /^\.(git|svn)$/
    });

will return:

    { undefined: OneOfMyControllers }

I'd say the quick fix is:

    var match = file.match(options.filter || /^(.+)$/);

I'd love to hear your thoughts.
Thanks.
Joe

**Comment by dougwilson** [comment]
It does, PRs welcome.

**Comment by jframbach-nerdwallet** [comment]
https://github.com/felixge/node-require-all/pull/19
