### ISSUE TITLE
New release with passing map function recursively?

### ISSUE THREAD

**Issue by dburrows** [felixge/node-require-all#23]
Hi,

Got bitten by a bug in the current release where it doesn't pass the map function down when it recurses directories - looks to be fixed in the current Master, any chance of a release with this fix?

Thanks in advance.

**Comment by dougwilson** [comment]
I'll work on getting a release cut :)

**Comment by dougwilson** [comment]
Published to npm as version 2.0.0.

**Comment by dburrows** [comment]
Thanks very much! :D
