### ISSUE TITLE
add option to skip requiring all if directory does not exist

### ISSUE THREAD

**Issue by PLEEROCK** [felixge/node-require-all#24]
Need to have ability not to do require-all in directories that does not exist, without manually checks if directory is actually exist. This is required to prevent errors like `ENOENT: no such file or directory`

**Comment by dougwilson** [comment]
Hi! This is something you would need to do in your call, as in don't call this module if you don't want to load the directory. Calling the function signals "I want to require the modules in this directory", thus if we can't do that, it's an error.
```js
var dir = __dirname + '/lib';
var libs = fs.existsSync(dir) ? require('require-all')(dir) : {};
```
