### ISSUE TITLE
Exclude files

### ISSUE THREAD

**Issue by raoulus** [felixge/node-require-all#27]
How do you think about having an option to exclude files as well? 

In my case I want to exclude a single file, let's say it's a json config which is used by some of the tasks.

I'd need this

``` javascript
require('require-all')({
  excludeFiles:  ['a.json', 'b.json', ...]
});
```

Best regards

**Comment by dougwilson** [comment]
Hi @raoulus! So far, we've been able to get away with just the `filter` argument, which is a regular expression. This argument is meant to filter the files to just the ones you want (which means it's both includes & excludes).

I kind of see two possible solutions here:

1. We can add the ability for the `filter` option to take a function instead of only a regular expression. This would allow literally any logic you could ever want.
2. You may be able to use a regular expression for your use-case.

What are your thoughts? An array of files as a different option may work, but not sure how it will play out with the recursive option in the long term.

**Comment by tauren** [comment]
I'd like to filter out certain files as well. For instance, I don't want to include `test` files. Assume I have the following files:

```
module1.js
module1.test.js
module2.js
module2.test.js
```

I'd like to return an object equivalent to this:

```
{
  module1: require("./module1"),
  module2: require("./module2")
}
```

I've tried using a negative lookahead regex, but it is including `test.js` files:

```
module.exports = require('require-all')({
  dirname     :  __dirname,
  filter      :  /^([^\.].+)(?!(\.test))\.js(on)?$/,
  recursive   : false
});
```

I believe this should be possible with a regex and I'm open to suggestions on how to do it. However, it may be simpler for less skilled regexers if filter could be a function as you suggest.

**Comment by tauren** [comment]
I was able to get my filter regex to work by moving the negative lookahead to the beginning:

```
module.exports = require('require-all')({
  dirname     :  __dirname,
  filter      :  /^(?!.*test\.js|index\.js)([^\.].+)\.js(on)?$/,
  recursive   : false
});
```

This will require all `.js` and `.json` file in the current directory, but exclude any files containing `index.js` or `*.test.js`.

**Comment by raoulus** [comment]
Yeah a function instead of a regex might be more user friendly :)

I really would like to see this in future.

**Comment by dougwilson** [comment]
Goo to hear, @tauren! I'm going to look at adding the ability to specify a `function` as well as a regular expression, in a moment here. I'm thinking the signature will probably be `var include = filter(filename, path)`, where `filename` is just the filename, the same string the regular expression tests against, and `path` is the built path from the `dirname` option plus the directories traversed, which would even allow you to make a function that excludes based on the full directory.

**Comment by ngprasad** [comment]
The referenced issue has been resolved looking at the checkin. Can someone please close this and update the documentation regarding what changes went in and how we can use the filter function?

Thanks,

**Comment by dougwilson** [comment]
Hi @ngprasad, this is still open because nothing has been checked in that I'm aware of. Can you point me to where it has been checked in?

**Comment by ngprasad** [comment]
I saw two checkins here: https://github.com/felixge/node-require-all/pull/31. I thought these were for the filter issue. I mistakenly made that assumption. So there has not been a resolution to this?

**Comment by dougwilson** [comment]
That is just a pull request for a possible solution, not actually a check in. Sorry GitHub is confusing :)

**Comment by ngprasad** [comment]
Oh i see. Can that PR please be reviewed? It will really helpful to have filter function/arrays instead of regex.

**Comment by dougwilson** [comment]
I have it on my backlog of items to do still :) I popped over to the pull request, and the diff is so large, I have to actually find some time to sit down and actually reason through it, and it does bot come with any documentation, so would have to understand it enough to write that up. Have you tried it to verify that it actually matches your use-case yet?

**Comment by AngryPidgeon** [comment]
Came here to open precisely this issue

For justice plz, it would be like 5 minutes of dev time.

**Comment by dougwilson** [comment]
Ok, @AngryPidgeon, I reviewed that PR. You'll either need to wait for the authro to get back to submit your own PR and I'll take a look.

**Comment by AngryPidgeon** [comment]
@dougwilson  I hadn't noticed the PR before.  Also I just spent a while messing around with the filter that is currently there and it appears bugged?  I think the hard-coded "1" on line 41 of index.js should be a 0. 

string.match(regex) returns an array like:

[ 'foo.js',
  index: 0,
  input: 'foo.js' ]

As it is, its taking the index of the match (arbitrary for this purpose) and mapping it to the required contents.  It looks like we should be mapping the filename (guaranteed unique) to the contents.

**Comment by dougwilson** [comment]
Hi @AngryPidgeon, it only appears "bugged" due to the lack of documentation. If you supply a regular expression, you need to include a matching group (that's how the default regular expression works and at least all the examples of the README--the little that there is). I have come to maintain this module from the previous author, and there was no README to speak of, so PRs to improve the README and certainly welcome!

**Comment by AngryPidgeon** [comment]
@dougwilson 
A matching group is just a ()....which I have included.  This is inconsistent behavior at BEST, look at line 29 and 41 in index.js.  The default behavior maps the filename to the contents of requiring it.  The filter approach maps it to... ??

I made and closed a PR to do this, but after reading your post and looking at it again I think its absolutely the best way to do it.

I dont think you are right about matching groups - Im using one and it is not working.  The result from String.match(Regex)[1] may as well be random.

**Comment by dougwilson** [comment]
Hi @AngryPidgeon, I really have no idea what you're saying I'm sorry. I didn't write this module, only oversee it currently, form the old maintainer. There should be a pretty good test suite to help make sure your changes are backwards-compatible, if the goal is to simply add the new function filter as described in this issue.
