### ISSUE TITLE
Accessing require file question

### ISSUE THREAD

**Issue by 1nfinite** [felixge/node-require-all#30]
Suppose I have declare
```js
var jsons = require('require-all')(__dirname + '/json');
```
and inside the json directory have filename `jsonfile1.json`, `jsonfile2.json`.

How could i access jsonfile1?

Similarly, if i have declare
```js
var js = require('require-all')(__dirname + '/js');
```
and inside the js directory i have `js1.js`, `js2.js`, `js3.js`.
And inside js1, i have `export.Module1()`, `export.Module2()`.

How could i access `export.Module1` in `js1.js`?

**Comment by dougwilson** [comment]
Hi @1nfinite,

> How could i access jsonfile1?

For your first example, the way you would access `jsonfile1` would be with `jsons.jsonfile1`.

> How could i access export.Module1 in js1.js?

For your second example, the way you would access `export.Module1` in `js1.js` would be with `js.js1.Module1`.

I hope that helps!
