### ISSUE TITLE
Could be useful if resolve includes file name.

### ISSUE THREAD

**Issue by jaimegomez** [felixge/node-require-all#36]
I've been doing this for a while, extending this module to provide the file name, which is easy because it's already extracted (`match[1]`), and I don't think it breaks any common use case.

To illustrate why this is useful, this is an example of something I do frequently:

```javascript
var gulp = require('gulp');

require('require-all')({
    dirname: __dirname + '/src/tasks',
    resolve: function(item, name) {
        gulp.task(name, item.deps, item.task);
    },
});
```

Example task:

```javascript
module.exports = {
    deps: [],
    task: function(done) {
        done();
    },
};
```

So this is very useful when filenames have some semantic meaning, and this small improvement makes this straightforward.

Added a [pull request](https://github.com/felixge/node-require-all/pull/35)!

**Comment by dougwilson** [comment]
It turns out from the conversation in the pull request, what you're really doing is trying to just iterate over the requires and perform an action. The above can be done using lodash (until `Object.entities` is added to the JavaScript language):
```js
_.each(require('require-all')(__dirname + '/src/gulp'), function(item, name) {
    gulp.task(name, item.deps, function(cb) {
        console.log(`Running task: ${name}...`);
        item.task(cb);
    });
});
```

And an example using no dependencies besides this module:
```js
each(require('require-all')(__dirname + '/src/gulp'), function(item, name) {
    gulp.task(name, item.deps, function(cb) {
        console.log(`Running task: ${name}...`);
        item.task(cb);
    });
});

function each(obj, fn) {
    Object.keys(obj).forEach(function(key) {
        fn(obj[key], key);
    });
}
```

I hope that helps!
