### ISSUE TITLE
Certain files won't get required

### ISSUE THREAD

**Issue by Redsandro** [felixge/node-require-all#39]
For some reason, certain files won't get require'd, although those files themselves are legal.

```
node@4.2.6
require-all@2.0.0
```

Ubuntu 16.04 LTS

I don't know how to debug this. The required files are not enumerable.

```
'use strict';

module.exports = require('require-all')({
	dirname		: __dirname,
	filter		: /^(?!index).+\.js$/,
	map(name, path) {
		console.log(path, name);
	}
});

// Expected to list all included files, but only runs once
for (let idx = 0, keys = Object.keys(module.exports), len = keys.length; idx < len; idx++) {
	let key = keys[idx];
	console.log('GOT MODULE:', key);	// undefined
}
```

The directory contains the following files:

* `getRequestType.js` works
* `getRequestLocations.js` does not work, returns `undefined`
* `getRequestSearches.js` works
* `getFakeQuotes.js` does not work, returns `undefined`

The scripts are big, and something causes `require-all` to skip them.

Assuming a normal `require` is used internally, the source shouldn't even matter.

__Note__ that all files work fine when importing manually. No errors.
__Note__ that everything works fine using [`require-dir-all`](https://www.npmjs.com/package/require-dir-all).
__Workaround:__ Use `require-dir-all`

**Comment by dougwilson** [comment]
Hi @Redsandro all this module does to load the file is just the standard Node.js `require()`: https://github.com/felixge/node-require-all/blob/master/index.js#L41

I have no idea how a module could do anything different. If you're not sure what change we need to make, can you help provide a repository or something that reproduces the issue we can take a look at?

**Comment by Redsandro** [comment]
@dougwilson I'm experiencing this in a bigger project. I did just figure out that 

```
var object		= require('require-all')(__dirname + '/myModules')
```

works fine, but

```
var object		= require(__dirname + '/myModules')
```

where `myModules/index.js` is

```
'use strict';

module.exports = require('require-all')({
	dirname		: __dirname
});
```

Doesn't. Some files work, some don't.

Is there anything obvious about the way I wrote that that I'm missing, before deductively slimming down my code into a reproduction?

**Comment by dougwilson** [comment]
Yes, your map function is returning undefined, not a string name like it should. If you remove that map, does it resolve your issue?

**Comment by Redsandro** [comment]
Oh, I misunderstood the function.
But my regex is wrong too then? Because this doesn't work either:

```
module.exports = require('require-all')({
	dirname		: __dirname,
	filter		: /^(?!index).+\.js$/
});
```

This does work:

module.exports = require('require-all')({
	dirname		: __dirname
});

**Comment by dougwilson** [comment]
Your regular expression has no capture group. Either your regular expression needs a capture group to get the name from or your map function needs to return a name. If neither do, then the module has no idea what property name to load your file under.

**Comment by Redsandro** [comment]
@dougwilson Oh shoot. I assumed it did a `/regex/.test(filename)` (which needs no capture group)

**Comment by Redsandro** [comment]
@dougwilson nope - this doesn't work either

```
'use strict';

module.exports = require('require-all')({
	dirname		: __dirname,
	filter		: /(.+)/
});
```

Let me know if this should work. If so, I should try to make a testcase. If not, I need to apologize for misunderstanding and taking up your time.

**Comment by dougwilson** [comment]
I think you need to add ^ and $ to anchor your regular expression. If that still does not work, please make a test case :)

**Comment by Redsandro** [comment]
@dougwilson it seems near impossible. When I remove tons of irrelevant code and leave a simple variant, suddenly it works. Unfortunately I cannot share the entire code base because I don't own the rights. But there must 

I made one wrong observation tho: It's not that some files work. All files work, or none of the files work.

When I remove the regex it works, or when I leave the regex but remove the rest of the app, it works too.

Something must be conflicting. I can't figure out if it's a logical or buggy conflict.

**Comment by Redsandro** [comment]
You were right. It is the regex. Using `/(get.+)\.js$/` works. I didn't notice it in the testcase because the `development` flag was not set on my newly created test environment. Causing the promises to ignore the `undefined` errors. Causing me to draw conclusions too quickly.

I used the regex wrongly. I thought it filtered files away. But the selector `(...)` is the name of the exported module.

This was my own fault. I should have used `/^(?!index)(.+)\.js$/` in stead of `/^(?!index).+\.js$/`.

I owe you an apology. I apologize for wasting your time. At the same time I want to thank you for your quick responses. 

:ice_cream: :fireworks: :confetti_ball:

**Comment by Redsandro** [comment]
Feeling slightly bad for crying wolf, I can close this issue now. :disappointed:

**Comment by Redsandro** [comment]
In my defense, I don't think I realized this behavior although I did read the `npm` page.
I assumed it was like a `/regex/.test(filename)` to filter out filenames, but the match also (re)names the export. I suggest adding this in the documentation.

**Comment by dougwilson** [comment]
Hi @Redsandro I just tried to better document the filter option in the README. Feel free to make a PR if there are any additions you think would help with docs!

**Comment by Redsandro** [comment]
@dougwilson perfect. :+1:
