### ISSUE TITLE
Not defined when inside module.exports

### ISSUE THREAD

**Issue by westlakem** [felixge/node-require-all#49]
I'm trying to require all of my services in the "services" directory

```
var Services = require('require-all')({
    dirname: __dirname + '/services',
    filter: /^(.+)\.js$/
});

module.exports = async(function (req, res, next){
    .... (my code)
}
```
If i put a breakpoint on the `module.exports` line and look at services:
```
Services 
Object {ServiceOne: Object}
```
but when I put a breakpoint into my code (inside module.exports) and call that code, I get a ReferenceError
```
Services
ReferenceError: Services is not defined
```

**Comment by dougwilson** [comment]
That would be how v8 works if you don't actually use the Service variable in the source code that is ".... (my code)" ; the debugger would not see the variable in a function it's not used in.

If this is not the case, I'm not sure how this module could actually influence that. I can take a look into it if you can provide full instruction steps by step on how to reproduce your issue. I tired to reproduce and saw what I described in the first paragraph.

**Comment by westlakem** [comment]
Not trying to do a "the other thing is better than yours" but require-directory seems to work

```
var requireDirecotry = require('require-directory'),
var whitelist = /\.js$/,
var Services = requireDirecotry(module, './services', {include: whitelist})
```

**Comment by dougwilson** [comment]
I mean, if one works for you vs another, there is no reason not to use a different module. Unless I can get instructions for how to reproduce, I have no idea what I'm supposed to do to change anything :)
