### ISSUE TITLE
Add option to drop empty folders from the result when recursive is set to "true"

### ISSUE THREAD

**Issue by kibertoad** [felixge/node-require-all#51]
Currently if there are subfolders in the directory, but there are no files matching the filter, empty object for the subfolder still gets added to the results, even though it is just a noise in such case.

**Comment by kibertoad** [comment]
@dougwilson If you approve of this change, I can produce a PR.

**Comment by kibertoad** [comment]
Never encountered num 2 either, so num 1 gets my vote. Can I proceed with that route, then?

**Comment by dougwilson** [comment]
Sure

**Comment by kibertoad** [comment]
@dougwilson Sorry, got distracted before I could finish this before, but now it is done :)
