### ISSUE TITLE
a file with the same name as a directory

### ISSUE THREAD

**Issue by syuilo** [felixge/node-require-all#57]
When enable `recursive` option, can not be acquired correctly if there is a file with the same name as the directory

e.g.
```
foo
--bar.js
--hoge.js
foo.js
buzz.js
```

any solutions? Thanks in advance!

**Comment by dougwilson** [comment]
Hi @syuilo ! In the current version of this module, there are three possible ways to resolve this naming overlap:

1. Provide a `filter` option that keeps the file extension in the key name. For example `filter: /^([^\.].*\.js(on)?)$/`
2. Provide a `map` option where your function will someone differentiate the names of files and folders so they don't end up with the same key. You can read more about this here: https://github.com/felixge/node-require-all#alternative-property-names
3. Rearrange your files and folders to not encounter this situation.

I hope this helps!

**Comment by syuilo** [comment]
Thank you very much @dougwilson!
