### ISSUE TITLE
consider updating excludeDirs to match against directories instead of file names

### ISSUE THREAD

**Issue by JustinHallquist** [felixge/node-require-all#59]
The user interface for this is confusing as `excludeDirs`, which signature declares it accepts a `dirname`, is being passed a `filename`. This seems contradictory and muddles what the contract is supposed to be.

https://github.com/felixge/node-require-all/blob/master/index.js#L16
```
  function excludeDirectory(dirname) {
    return !recursive ||
      (excludeDirs && dirname.match(excludeDirs));
}
```

https://github.com/felixge/node-require-all/blob/master/index.js#L38
```
  files.forEach(function (file) {
    var filepath = dirname + '/' + file;
    if (fs.statSync(filepath).isDirectory()) {

    if (excludeDirectory(file)) return;
```

Would it not add more clarity to instead allow the regex to match against the directory itself?

That would prevent the need for obfuscated lookbehind/lookahead regex patterns in the `filter`

thoughts?

**Comment by dougwilson** [comment]
It does filter against directory names, not file names. Can you provide a test case or demo demonstrating that is is incorrectly filtering against file names?

**Comment by JustinHallquist** [comment]
thanks for the prompt response -- dug in as asked

so to preface, the misunderstanding is indeed on my end.

it does match against dir names, i was expecting it to match against the full path. the example isn't too clear on the matter and there is no other documentation around it that I saw.

```
 └──   a/
 │  └────   b/
 │  │  └────     c/
 │  │  │  └────     test.js
 ├──  index.js
 ├──  package-lock.json
 └──  package.json
```

```
excludeDirectory fn: dirname: a excludeDirs: /a\/b\/c/
excludeDirectory fn: dirname: b excludeDirs: /a\/b\/c/
excludeDirectory fn: dirname: c excludeDirs: /a\/b\/c/
excludeDirectory fn: dirname: node_modules excludeDirs: /a\/b\/c/
excludeDirectory fn: dirname: require-all excludeDirs: /a\/b\/c/
{
  a: { b: { c: [Object] } },
  index: {},
}
```

scanned through the code and saw
`if (excludeDirectory(file)) return;`

but missed 
`if (fs.statSync(filepath).isDirectory()) {`

which should have tipped me off
