### ISSUE TITLE
TypeError: fs.readdirSync is not a function

### ISSUE THREAD

**Issue by vishalc129** [felixge/node-require-all#60]
fs.readdirSync and fs.statSync functions doesnot exists in require('fs');
Please find alternate

**Comment by dougwilson** [comment]
https://nodejs.org/dist/latest-v12.x/docs/api/fs.html#fs_fs_readdirsync_path_options

https://nodejs.org/dist/latest-v12.x/docs/api/fs.html#fs_fs_statsync_path_options

**Comment by vishalc129** [comment]
@dougwilson  
installed fs from using 'npm i fs' from https://www.npmjs.com/package/fs . 
Installed version - 0.0.1-security

Please advise from where to install and what version

**Comment by dougwilson** [comment]
Modules that are part of node.js like fs do not need to be installed.

**Comment by vishalc129** [comment]
if i go by the default - and debug inside require-all, i'm getting fs as below
![image](https://user-images.githubusercontent.com/38748244/72199048-4788ba80-345c-11ea-9332-e9914b292d3b.png)

Please let me know where i'm going wrong

**Comment by dougwilson** [comment]
I'm not sure, that `fs` doesn't look at all like the `fs` included with Node.js. What version of Node.js are you running this on? If your `fs` does not have a `fs.readdirSync`, what methods does it have?

**Comment by vishalc129** [comment]
node version - v12.14.1 
you can check the fs object in console of above given screenshot.

**Comment by dougwilson** [comment]
Weird, I think you may have something wrong with your Node.js installation, then. You may want to open an issue with Node.js to help determine what is wrong with your system, as I'm not sure there is anything I can do in this module, as the only purpose of this module is to read the list of files from the file system.

In my first comment https://github.com/felixge/node-require-all/issues/60#issuecomment-573030763 I linked to the 12.14.1 docs for the `fs` methods I'm using, so it would seem to indicate that if you're missing them, there is something wrong with your Node.js install.
