### ISSUE TITLE
Support for esm module?

### ISSUE THREAD

**Issue by olawalejuwonm** [felixge/node-require-all#64]
I encountered this error when using esm module
![image](https://user-images.githubusercontent.com/52759812/184871879-ecdae15e-3ef0-4261-930b-111a39ecd466.png)

**Comment by rodrigooler** [comment]
> I encountered this error when using esm module ![image](https://user-images.githubusercontent.com/52759812/184871879-ecdae15e-3ef0-4261-930b-111a39ecd466.png)

Dear friend, I believe it doesn't work, I looked at the issues here and at README.md and I didn't find anything... so I believe that unfortunately it doesn't.

**Comment by dougwilson** [comment]
Hi, sorry for the lack of response to your issue. This module is made to `require()` all the files, hence the name. Node.js does not alloe you to `require()` esm modules, only `import` them, so it would be beyond the scope of this module.
