### ISSUE TITLE
"path" parameter is always unused in filter

### ISSUE THREAD

**Issue by MrEAlderson** [felixge/node-require-all#66]
https://www.npmjs.com/package/@types/require-all

Supposedly the filter function has a path argument, which unfortunately isn't actually being included, thereby it always returns undefined.

**Comment by dougwilson** [comment]
Hello, and very sorry for any confusion. There is no second parameter for the filter function by the module. It looks like those types just need to be fixed, which are maintained by the DefinitelyTyped project and the issue would need to be reported there. Sorry about that.
